apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cloud-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1          # Correct API group for Deployment
    kind: Deployment             # Make sure it's exactly "Deployment"
    name: cloud-app              # Must match your Deployment's metadata.name
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
