apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-app
  template:
    metadata:
      labels:
        app: cloud-app
    spec:
      containers:
      - name: cloud-app
        image: aftenidaniela/cloud-app:latest
        ports:
        - containerPort: 8080
