apiVersion: v1
kind: Service
metadata:
  name: cloud-app
spec:
  type: NodePort
  selector:
    app: cloud-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007  # Optional, or leave blank to auto-assign
