name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main  # or 'master'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build the JAR file
        run: ./gradlew bootJar

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: aftenidaniela/cloud-app:latest

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "apiVersion: v1
          clusters:
          - cluster:
              certificate-authority-data: ${{ secrets.MINIKUBE_CA }}
              server: https://127.0.0.1:52523
            name: minikube
          contexts:
          - context:
              cluster: minikube
              namespace: default
              user: minikube
            name: minikube
          current-context: minikube
          kind: Config
          preferences: {}
          users:
          - name: minikube
            user:
              client-certificate-data: ${{ secrets.MINIKUBE_CLIENT_CERT }}
              client-key-data: ${{ secrets.MINIKUBE_CLIENT_KEY }}" > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/deployment.yaml --validate=false
