name: DockerHub Rollback

on:
  workflow_dispatch:

jobs:
  rollback:
    runs-on: [self-hosted, Windows, X64]

    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/cloud-app

    steps:
    - name: Get Docker tags from DockerHub
      id: tags
      shell: powershell
      run: |
        $headers = @{ "Accept" = "application/json" }
        $uri = "https://hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USERNAME }}/cloud-app/tags?page_size=2&page=1&ordering=last_updated"
        $response = Invoke-RestMethod -Uri $uri -Headers $headers
        $rollbackTag = $response.results[1].name
        echo "rollback_tag=$rollbackTag" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

    - name: Show tag being rolled back to
      run: echo "Rolling back to image tag: ${{ steps.tags.outputs.rollback_tag }}"
      shell: powershell

    - name: Update Kubernetes deployment to previous tag
      run: kubectl set image deployment/cloud-app cloud-app=${{ env.IMAGE_NAME }}:${{ steps.tags.outputs.rollback_tag }}
      shell: powershell
